<script lang="ts">
  import Icon from './Icon.svelte';
  import JsonPanel from './JsonPanel.svelte';
  import { knowledgeLabel, readable, rejectionLabel, time } from '../lib/presentation.ts';
  import type { LabView, PlanningRequest, PlanningResult } from '../lib/contracts.ts';
  let { view, result, request }: { view: LabView; result: PlanningResult | null; request: PlanningRequest } = $props();
  const semanticObjects = $derived(request.context.objects.filter((object) => object.semantics !== null));
</script>

{#if view === 'Trace'}
  <section class="panel inspector-panel"><div class="panel-heading"><div><span class="eyebrow">DETERMINISTIC EVIDENCE</span><h2>Follow the decision</h2></div><Icon name="trace" /></div>
    {#if result}<div class="trace-flow"><div><span>01</span><strong>Request validation</strong><small>{readable(result.validation.state)}</small></div><span>→</span><div><span>02</span><strong>Search</strong><small>{result.search_space.evaluated} grid positions</small></div><span>→</span><div><span>03</span><strong>Proposals</strong><small>{result.candidates.length} feasible candidates</small></div></div><JsonPanel title="Validation report" value={result.validation} open={result.validation.issues.length > 0} /><JsonPanel title="Declared search space" value={result.search_space} />
    <h3 class="subheading">Rejected placements <span>{result.conflicts.rejections.length}</span></h3><div class="table-wrap"><table><thead><tr><th>Start / UTC</th><th>Reasons from the core</th></tr></thead><tbody>{#each result.conflicts.rejections.slice(0, 64) as rejection}<tr><td>{time(rejection.start)}</td><td>{#each rejection.reasons as reason}<span class="rejection-reason">{rejectionLabel(reason)}</span>{/each}</td></tr>{:else}<tr><td colspan="2">No placement rejections returned.</td></tr>{/each}</tbody></table></div><p class="fine-print">First 64 rejections. A conflict set is evidence for the declared search space; it is not claimed minimal.</p><JsonPanel title="All conflicts / source data" value={result.conflicts} />
    {:else}<div class="large-empty"><Icon name="trace" size={38} /><h3>No trace yet</h3><p>Run a request or import a PlanningResult to inspect validation, search and rejection evidence.</p></div>{/if}
  </section>
{:else if view === 'Preferences'}
  <section class="panel inspector-panel"><div class="panel-heading"><div><span class="eyebrow">INTERPRETABLE RANKING</span><h2>What shapes the score</h2></div><Icon name="preferences" /></div><p class="panel-description">Explicit request → session context → personal learned → global learned → default. Learning remains a future milestone.</p><div class="preference-order">{#each ['Explicit', 'Session', 'Personal', 'Global', 'Default'] as source, index}<div class:accent={index === 0}><small>0{index + 1}</small><strong>{source}</strong></div>{/each}</div><h3 class="subheading">Current request evidence</h3><div class="table-wrap"><table><thead><tr><th>Source</th><th>Preferred start / UTC</th><th>Evidence IDs</th></tr></thead><tbody>{#each request.preferences.preferences as preference}<tr><td>{readable(preference.source)}</td><td>{time(preference.preferred_start)}</td><td>{preference.evidence.join(', ') || 'None supplied'}</td></tr>{:else}<tr><td colspan="3">No preference supplied. The baseline uses a deterministic earliest-start tie break.</td></tr>{/each}</tbody></table></div><JsonPanel title="Preference profile" value={request.preferences} />{#if result}<JsonPanel title="Returned score components" value={result.candidates.map((candidate) => ({ start: candidate.start, cost: candidate.cost, explanation: candidate.explanation }))} />{/if}</section>
{:else if view === 'Semantics'}
  <section class="panel inspector-panel"><div class="panel-heading"><div><span class="eyebrow">EVIDENCE / NOT HARD RULES</span><h2>Meaning with provenance</h2></div><Icon name="semantics" /></div><p class="panel-description">Semantic values are inspected as supplied in the CPIR snapshot. Unknown and missing values stay explicit.</p>{#each semanticObjects as object}<h3 class="subheading">{object.id}</h3><div class="semantic-grid">{#each Object.entries(object.semantics!) as [name, field]}<article><small>{readable(name)}</small><strong>{knowledgeLabel(field)}</strong><span>{readable(field.provenance)}</span><JsonPanel title="Evidence" value={field} /></article>{/each}</div>{:else}<div class="large-empty"><span class="orb"><Icon name="semantics" size={38} /></span><h3>No semantic profile supplied</h3><p>This request contains no semantic vectors. Import evidence to inspect it here; model-generated signals are deferred.</p></div>{/each}</section>
{:else}
  <section class="panel inspector-panel reserved-panel"><span class="eyebrow">RESERVED LEARNING MILESTONE</span><div class="large-empty"><span class="orb"><Icon name={view === 'ML' ? 'ml' : 'dataset'} size={44} /></span><span class="badge subtle">NOT CONNECTED</span><h2>{view === 'ML' ? 'A place to understand the model.' : 'Good data. Visible evidence.'}</h2><p>{view === 'ML' ? 'This workspace will expose versioned experiments, training curves, calibration and inference traces as the learning milestones are implemented.' : 'This workspace will expose dataset versions, splits, class distributions and challenge-set results when dataset tooling is implemented.'}</p></div><div class="future-grid">{#each view === 'ML' ? ['Experiment comparison', 'Training & evaluation', 'Model output traces'] : ['Versioned manifests', 'Quality & distributions', 'Challenge-set explorer'] as item}<div><Icon name="code" size={18} /><span>{item}</span><small>PLANNED</small></div>{/each}</div><p class="fine-print">{view === 'ML' ? 'No training, inference or learned ranking is performed by this UI.' : 'The bundled synthetic planning request is a demo fixture, not a training or evaluation dataset.'}</p></section>
{/if}
