<script lang="ts">
  import { base } from '$app/paths';
  import SourceLink from '$lib/components/SourceLink.svelte';
  import StatusBadge from '$lib/components/StatusBadge.svelte';
  import SystemVisual from '$lib/components/SystemVisual.svelte';
  import VisualizationFrame from '$lib/components/VisualizationFrame.svelte';
  import { runtimeData } from '$lib/generated/runtime-data';

  let { data } = $props();
  const section = data.section;
  const textAlternatives: Record<string, string> = {
    atlas: 'A central Cerebri node connects to Temporal, CPIR, Constraints, Planner and Validation. A visually distinct Research node sits outside the implemented core.',
    cpir: 'Four panels summarize canonical request identity, knowledge/provenance, policy and search budget from examples/request.json.',
    planning: 'A three-hour timeline shows one known busy block followed by deterministic candidate slots. A result panel states the planner outcome, assessment and candidate count from Rust output.',
    time: 'Cards explain half-open intervals, DST gaps and DST folds, with raw temporal diagnostic output available in a disclosure.',
    safety: 'A one-way chain progresses from PlanningRequest through ProposedPlan, ValidatedPlan, ActionPlan and AuthorizedActionPlan to ExecutionResult.',
    architecture: 'Layered boxes show types and temporal foundations, middle semantic/constraint layers, planner, core facade and thin transports.',
    roadmap: 'Four horizontal strata show implemented Foundation and Temporal Core, the next deterministic planner target, and later provider/repair/learning/neural work.',
    developers: 'A code window lists validate, plan and temporal REST routes and explicitly shows that execute is absent, followed by a transport-to-core flow.',
    lab: 'Three panes show planner inspection, temporal diagnostics and an inactive reserved ML/dataset surface.'
  };
</script>

<svelte:head>
  <title>{section.eyebrow} · Nexus Cerebri</title>
  <meta name="description" content={section.summary} />
</svelte:head>

<section class="page-hero">
  <div>
    <div class="hero-meta"><StatusBadge status={section.status} /><span>{section.truth}</span></div>
    <p class="kicker">{section.eyebrow}</p>
    <h1>{section.title}</h1>
    <p class="page-summary">{section.summary}</p>
    <div class="depth-technical depth-panel">
      <small>TECHNICAL DEPTH</small>
      <p>{section.technical}</p>
    </div>
    <div class="depth-research depth-panel research">
      <small>RESEARCH DEPTH</small>
      <p>{section.research}</p>
    </div>
    <SourceLink path={section.sourcePath} label={section.sourceLabel} />
  </div>
  <aside class="principle-list" aria-label="Key boundaries">
    {#each section.bullets as bullet, index}
      <div><span>{String(index + 1).padStart(2, '0')}</span><p>{bullet}</p></div>
    {/each}
  </aside>
</section>

<VisualizationFrame
  kind={section.truth}
  label={section.eyebrow}
  caption={section.truth === 'REAL'
    ? 'Built from current repository facts or Rust-generated fixture output.'
    : section.truth === 'EDUCATIONAL'
      ? 'An explanatory diagram of documented architecture; not a live runtime trace.'
      : 'A future-facing concept that is not implemented.'}
  textAlternative={textAlternatives[section.visual]}
>
  <SystemVisual visual={section.visual} />
</VisualizationFrame>

{#if data.key === 'lab'}
  <section class="callout">
    <div>
      <span class="kicker">SEPARATE DEVELOPER SURFACE</span>
      <h2>Lab stays independent.</h2>
      <p>The official site explains the Lab boundary but does not absorb its API-driven inspection tools.</p>
    </div>
    <a class="secondary-action" href={base + '/docs/project/'}>Project entry points</a>
  </section>
{:else if data.key === 'planning'}
  <section class="callout">
    <div>
      <span class="kicker">CURRENT CORE RESULT</span>
      <h2>{(runtimeData.plannerResult as any).assessment ?? 'Structured planner assessment'}</h2>
      <p>The value above is generated by running the Rust core example during the website build.</p>
    </div>
    <a class="secondary-action" href={base + '/docs/architecture/decisions/ADR-0006-search-transports/'}>Read ADR-0006</a>
  </section>
{/if}
