import { readFile, readdir, mkdir, writeFile, copyFile, rm } from 'node:fs/promises';
import { resolve, relative, dirname, sep, basename } from 'node:path';
import MarkdownIt from 'markdown-it';

const root=process.cwd(), destination=resolve(root,'site');
if(dirname(destination)!==root || relative(root,destination)!=='site') throw new Error('unsafe generated output path');
await rm(destination,{recursive:true,force:true});
const cargo=await readFile('Cargo.toml','utf8');
const version=cargo.match(/\[workspace\.package\][\s\S]*?version = "([^"]+)"/)?.[1] ?? 'development';
const master=await readFile('docs/architecture/specifications/master-v0.4.md','utf8').catch(()=> '');
const spec=master.match(/Specification version:\*\*\s*([0-9.]+)/)?.[1] ?? '0.4';
const md=new MarkdownIt({html:true,linkify:false,typographer:false});
const baseLink=md.renderer.rules.link_open||((t,i,o,e,s)=>s.renderToken(t,i,o));
md.renderer.rules.link_open=(t,i,o,e,s)=>{const h=t[i].attrGet('href');if(h&&!/^(?:[a-z]+:|#)/i.test(h))t[i].attrSet('href',h.replace(/\.md(?=#|$)/,'.html'));return baseLink(t,i,o,e,s)};
async function walk(dir){let r=[];for(const e of await readdir(dir,{withFileTypes:true})){if(['.git','.idea','target','node_modules','site','dist'].includes(e.name))continue;const p=resolve(dir,e.name);r.push(...(e.isDirectory()?await walk(p):p.endsWith('.md')?[p]:[]))}return r}
const files=await walk(root);
const esc=s=>s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const pretty=s=>s.replace(/\.md$/,'').replace(/README$/i,'Overview').replace(/[-_]/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const category=rel=>rel==='CHANGELOG.md'||rel==='README.md'?'Project':rel.split(sep)[0]==='docs'?pretty(rel.split(sep)[1]||'Documentation'):'Project';
const navItems=files.filter(p=>{const r=relative(root,p);return r==='CHANGELOG.md'||r==='README.md'||r==='docs/README.md'||r.startsWith('docs'+sep)}).map(p=>({rel:relative(root,p),title:pretty(basename(p)),group:category(relative(root,p))}));
const navStatic=[['Home','index.html'],['Changelog','CHANGELOG.html'],['Documentation','docs/README.html'],['English','docs/en/README.html'],['Deutsch','docs/de/README.html'],['Master Spec','docs/architecture/specifications/master-v0.4.html'],['Roadmap','docs/development/roadmap/README.html'],['ADRs','docs/architecture/decisions/ADR-0001-workspace.html'],['Testing','docs/testing/testing-visualization-research-standard.html'],['Cerebri Lab','apps/cerebri-lab/README.html']];
const rootPrefix=rel=>'../'.repeat(rel.split(sep).length-1);
function nav(prefix,current){const groups=[['PORTAL',navStatic.slice(0,3)],['LANGUAGE',navStatic.slice(3,5)],['KNOWLEDGE',navStatic.slice(5)]];return groups.map(([g,it])=>`<div class="nav-title">${g}</div>${it.map(([n,p])=>`<a class="${p===current?'active':''}" href="${prefix}${p}"><i></i>${n}</a>`).join('')}`).join('')}
function shell(rel,title,content){const prefix=rootPrefix(rel);return `<!doctype html><html lang="${rel.includes('docs'+sep+'de'+sep)?'de':'en'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#050713"><title>${esc(title)} · Nexus Cerebri</title><link rel="stylesheet" href="${prefix}assets/portal.css"></head><body data-root="${prefix}"><div class="bg"></div><aside class="sidebar"><a class="brand" href="${prefix}index.html"><img src="${prefix}assets/nexus-cerebri-logo.png" alt=""><span><strong>Nexus Cerebri</strong><small>KNOWLEDGE SYSTEM</small></span></a><nav class="nav">${nav(prefix,rel)}</nav></aside><div class="shell"><header class="topbar"><button class="menu" aria-label="Toggle navigation">☰</button><div class="crumb">NEXUS / ${esc(title.toUpperCase())}</div><div class="top-actions"><button class="pill" data-search>⌘ K &nbsp; Search</button><a class="pill hide-mobile" href="${prefix}CHANGELOG.html">Changelog</a><a class="pill hide-mobile" href="https://github.com/YoungJibbit95/Nexus-Cerebri">GitHub ↗</a></div></header><main>${content}</main><footer><span>Neural intuition. Symbolic verification.</span><span>Software ${esc(version)} · Spec ${esc(spec)} · Repository-native documentation.</span></footer></div><dialog id="search"><div class="search-head"><input placeholder="Search documentation…" aria-label="Search documentation"><button data-close>×</button></div><div class="results"></div></dialog><script src="${prefix}assets/portal.js"></script></body></html>`}
const home=`<section class="hero"><div><span class="eyebrow">NEXUS CEREBRI / OPEN RESEARCH</span><h1>Reason freely.<br><em>Verify everything.</em></h1><p>A temporal planning foundation where neural intuition and symbolic verification interlock. Documentation, architecture, research and project history in one living knowledge system.</p><div class="actions"><a class="primary" href="docs/README.html">Explore documentation →</a><a class="secondary" href="docs/de/README.html">Deutsch</a><a class="secondary" href="docs/en/README.html">English</a></div></div><div class="logo-stage"><div class="halo"></div><img src="assets/nexus-cerebri-logo.png" alt="Nexus Cerebri"></div></section>
<section class="stats"><article class="stat"><small>SOFTWARE</small><strong>${esc(version)}</strong><span>Temporal Core research</span></article><article class="stat"><small>SPECIFICATION</small><strong>${esc(spec)}</strong><span>Foundation baseline</span></article><article class="stat"><small>CPIR</small><strong>0.1</strong><span>Internal schema</span></article><article class="stat"><small>PRINCIPLE</small><strong>Hybrid</strong><span>intuition × verification</span></article></section>
<section class="dashboard"><article class="glass"><span class="eyebrow">PLANNING LIFECYCLE</span><h2>Clear boundaries from meaning to mutation.</h2><p>The planner proposes. Deterministic validation and authorization guard what can become executable.</p><div class="pipeline"><span>Input</span><b>→</b><span>CPIR</span><b>→</b><span>Planner</span><b>→</b><span>Validation</span><b>→</b><span>ActionPlan</span><b>→</b><span>Authorization</span><b>→</b><span>Executor</span></div><div class="matrix"><div><b>LAYER</b><b>ROLE</b><b>TRUST</b></div><div><span>Interpretation</span><span>Meaning & inference</span><em>Probabilistic</em></div><div><span>Planning</span><span>Candidate search</span><em>Bounded</em></div><div><span>Validation</span><span>Constraint proof</span><em>Deterministic</em></div><div><span>Execution</span><span>Authorized mutation</span><em>Guarded</em></div></div></article><article class="glass"><span class="eyebrow">SYSTEM MAP</span><h2>Interlocking concepts.</h2><div class="mindmap"><div class="mind-core">CEREBRI</div><div class="node n1">Temporal</div><div class="node n2">CPIR</div><div class="node n3">Constraints</div><div class="node n4">Validation</div><div class="node n5">Planning</div><div class="node n6">Research</div></div></article></section>
<div class="section-title"><span class="eyebrow">EXPLORE</span><h2>One portal. Four useful entry points.</h2></div><section class="cards"><a class="glass link-card" href="docs/architecture/specifications/master-v0.4.html"><b>01 / ARCHITECTURE</b><strong>Master Specification</strong><span>Normative system architecture and invariants.</span></a><a class="glass link-card" href="docs/development/roadmap/README.html"><b>02 / DEVELOPMENT</b><strong>Roadmap</strong><span>Current milestones and the path forward.</span></a><a class="glass link-card" href="CHANGELOG.html"><b>03 / HISTORY</b><strong>Changelog</strong><span>Software and specification changes.</span></a><a class="glass link-card" href="docs/README.html"><b>04 / WIKI</b><strong>Knowledge map</strong><span>Browse all repository documentation.</span></a></section>`;
await mkdir(destination,{recursive:true});
for(const path of files){const rel=relative(root,path);const out=resolve(destination,rel.replace(/\.md$/,'.html'));const raw=(await readFile(path,'utf8')).replace(/^<!-- doc:[^]*?-->\s*/,'');const first=raw.match(/^#\s+(.+)$/m)?.[1]?.replace(/[*`#]/g,'')??pretty(basename(path));const body=`<div class="doc-grid"><article class="document glass"><div class="eyebrow">${esc(category(rel))}</div>${md.render(raw)}</article><aside class="toc"><strong>ON THIS PAGE</strong><div class="toc-links"></div></aside></div>`;await mkdir(dirname(out),{recursive:true});await writeFile(out,shell(rel.replace(/\.md$/,'.html'),first,body))}
await writeFile(resolve(destination,'index.html'),shell('index.html','Home',home));
await writeFile(resolve(destination,'.nojekyll'),'');
await mkdir(resolve(destination,'assets'),{recursive:true});
for(const [src,dst] of [['scripts/docs-theme.css','assets/portal.css'],['scripts/docs-ui.js','assets/portal.js'],['assets/nexus-cerebri-logo.png','assets/nexus-cerebri-logo.png']])await copyFile(resolve(root,src),resolve(destination,dst));
for(const f of ['request.json','temporal-request.json']){await mkdir(resolve(destination,'examples'),{recursive:true});await copyFile(resolve(root,'examples',f),resolve(destination,'examples',f))}
await writeFile(resolve(destination,'search-index.json'),JSON.stringify(navItems.map(x=>({title:x.rel==='CHANGELOG.md'?'Changelog':x.title,path:x.rel.replace(/\.md$/,'.html').split(sep).join('/'),group:x.group}))));
console.log(`Cerebri Portal V3 built: ${files.length} Markdown sources -> site/`);
